import { PropsWithChildren } from 'react'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type LayoutProps = PropsWithChildren & {
  modal: React.ReactNode
}

export default function Layout(props: LayoutProps) {
  // console.log(props.modal)
  return (
    <html lang="ja">
      <body>
        {props.children}
        {props.modal}
      </body>
    </html>
  )
}
